#!/bin/bash

echo "🔍 Checking Firebase Database Rules..."
echo ""
echo "Opening Firebase Console in your browser..."
echo ""

# Open Firebase Console
open "https://console.firebase.google.com/project/insportsathon/database/insportsathon-default-rtdb/rules"

echo "✅ Browser opened!"
echo ""
echo "📋 What you'll see:"
echo ""
echo "1. Firebase Console will open"
echo "2. You'll see the Realtime Database Rules editor"
echo "3. Current rules will be displayed in JSON format"
echo ""
echo "⚠️ If you see this (TEST MODE - INSECURE):"
echo "   {"
echo "     \"rules\": {"
echo "       \".read\": true,"
echo "       \".write\": true"
echo "     }"
echo "   }"
echo ""
echo "   This means ANYONE can read/write your database!"
echo "   You need to update the rules immediately."
echo ""
echo "✅ You want to see this (SECURE MODE):"
echo "   {"
echo "     \"rules\": {"
echo "       \"tournaments\": { ... },"
echo "       \"users\": { ... },"
echo "       \"contacts\": { ... }"
echo "     }"
echo "   }"
echo ""
echo "📝 To update rules:"
echo "   1. Copy contents from: database.rules.json"
echo "   2. Paste in the Firebase Console editor"
echo "   3. Click 'Publish' button (top right)"
echo ""

